version: '3'
services:

  redis:
    restart: always
    image: redis:latest
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - /opt/relay/redis:/data

  relay:
#    build: .
    image: imashen/pub-relay:latest
    restart: always
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:5555:5555"
    depends_on:
      - redis
    volumes:
      - /opt/relay/.env:/relay/.env:ro
      - /opt/relay/actor.pem:/relay/data/actor.pem:ro

networks:
  external_network:
  internal_network:
    internal: true