name: Manual Build Docker Image

on:
  push:
    paths:
      - "ReleaseTag"
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: 🔍Checkout
        uses: actions/checkout@v2

      # Docker Image 构建环境
      - name: 🗳️Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: 🗳️Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 🤖Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 获得仓库中的ReleaseTag
      - name: 🗳️Set Version
        id: set-version
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      # Build and push
      
      - name: ⚓ Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            imashen/pub-relay:dev
            imashen/pub-relay:dev-${{steps.set-version.outputs.sha_short}}
